-- Migration 031: SUPERSEDED — DO NOT RUN ON NEW ENVIRONMENTS
--
-- This migration originally introduced a per-auction `activated_at` column
-- under the (incorrect) business rule that the seller pays $1 to activate
-- an auction globally. That rule has been REPLACED by a per-user / per-auction
-- buyer-side unlock model, implemented by:
--
--   • Migration 032 — creates the `auction_unlocks` table.
--   • Migration 033 — drops the `auctions.activated_at` column and its index.
--
-- This file is kept (instead of deleted) so the migration log on environments
-- where 031 already ran has a consistent on-disk record. New environments
-- should skip 031 and apply 032 and 033 directly.
--
-- The original SQL (now a no-op intentionally) was:
--   ALTER TABLE auctions ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ;
--   CREATE INDEX IF NOT EXISTS idx_auctions_locked
--     ON auctions (id) WHERE activated_at IS NULL;

-- (intentionally empty)
